In [119]:
import pandas as pd
import numpy as np

In [120]:
import statistics as s

In [121]:
df=pd.read_csv("D://NEW PROJECT//Iris.csv",sep=",")

In [122]:
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [123]:
df1=df[["SepalWidthCm"]]

In [124]:
df1

SepalWidthCm
0             3.5
1             3.0
2             3.2
3             3.1
4             3.6
5             3.9
6             3.4
7             3.4
8             2.9
9             3.1
10            3.7
11            3.4
12            3.0
13            3.0
14            4.0
15            4.4
16            3.9
17            3.5
18            3.8
19            3.8
20            3.4
21            3.7
22            3.6
23            3.3
24            3.4
25            3.0
26            3.4
27            3.5
28            3.4
29            3.2
..            ...
120           3.2
121           2.8
122           2.8
123           2.7
124           3.3
125           3.2
126           2.8
127           3.0
128           2.8
129           3.0
130           2.8
131           3.8
132           2.8
133           2.8
134           2.6
135           3.0
136           3.4
137           3.1
138           3.0
139           3.1
140           3.1
141           3.1
142           2.7
143           3.2
144           3.3
145           3.0
146           2.5
147           3.0
148           3.4
149           3.0

[150 rows x 1 columns]

In [125]:
import itertools
it = itertools.repeat(1,150)

In [126]:
it

repeat(1, 150)

In [127]:
a=np.repeat(1,150)

In [128]:
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [129]:
x=pd.DataFrame(a)

In [130]:
x

0
0    1
1    1
2    1
3    1
4    1
5    1
6    1
7    1
8    1
9    1
10   1
11   1
12   1
13   1
14   1
15   1
16   1
17   1
18   1
19   1
20   1
21   1
22   1
23   1
24   1
25   1
26   1
27   1
28   1
29   1
..  ..
120  1
121  1
122  1
123  1
124  1
125  1
126  1
127  1
128  1
129  1
130  1
131  1
132  1
133  1
134  1
135  1
136  1
137  1
138  1
139  1
140  1
141  1
142  1
143  1
144  1
145  1
146  1
147  1
148  1
149  1

[150 rows x 1 columns]

In [131]:
result=pd.concat([x,df1],axis=1)

In [132]:
result

0  SepalWidthCm
0    1           3.5
1    1           3.0
2    1           3.2
3    1           3.1
4    1           3.6
5    1           3.9
6    1           3.4
7    1           3.4
8    1           2.9
9    1           3.1
10   1           3.7
11   1           3.4
12   1           3.0
13   1           3.0
14   1           4.0
15   1           4.4
16   1           3.9
17   1           3.5
18   1           3.8
19   1           3.8
20   1           3.4
21   1           3.7
22   1           3.6
23   1           3.3
24   1           3.4
25   1           3.0
26   1           3.4
27   1           3.5
28   1           3.4
29   1           3.2
..  ..           ...
120  1           3.2
121  1           2.8
122  1           2.8
123  1           2.7
124  1           3.3
125  1           3.2
126  1           2.8
127  1           3.0
128  1           2.8
129  1           3.0
130  1           2.8
131  1           3.8
132  1           2.8
133  1           2.8
134  1           2.6
135  1           3.0
136  1           3.4
137  1           3.1
138  1           3.0
139  1           3.1
140  1           3.1
141  1           3.1
142  1           2.7
143  1           3.2
144  1           3.3
145  1           3.0
146  1           2.5
147  1           3.0
148  1           3.4
149  1           3.0

[150 rows x 2 columns]

In [133]:
m=pd.DataFrame.as_matrix(result,columns=None)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [134]:
m

array([[1. , 3.5],
       [1. , 3. ],
       [1. , 3.2],
       [1. , 3.1],
       [1. , 3.6],
       [1. , 3.9],
       [1. , 3.4],
       [1. , 3.4],
       [1. , 2.9],
       [1. , 3.1],
       [1. , 3.7],
       [1. , 3.4],
       [1. , 3. ],
       [1. , 3. ],
       [1. , 4. ],
       [1. , 4.4],
       [1. , 3.9],
       [1. , 3.5],
       [1. , 3.8],
       [1. , 3.8],
       [1. , 3.4],
       [1. , 3.7],
       [1. , 3.6],
       [1. , 3.3],
       [1. , 3.4],
       [1. , 3. ],
       [1. , 3.4],
       [1. , 3.5],
       [1. , 3.4],
       [1. , 3.2],
       [1. , 3.1],
       [1. , 3.4],
       [1. , 4.1],
       [1. , 4.2],
       [1. , 3.1],
       [1. , 3.2],
       [1. , 3.5],
       [1. , 3.1],
       [1. , 3. ],
       [1. , 3.4],
       [1. , 3.5],
       [1. , 2.3],
       [1. , 3.2],
       [1. , 3.5],
       [1. , 3.8],
       [1. , 3. ],
       [1. , 3.8],
       [1. , 3.2],
       [1. , 3.7],
       [1. , 3.3],
       [1. , 3.2],
       [1. , 3.2],
       [1. ,

In [135]:
y=df.SepalLengthCm

In [136]:
y

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [137]:
b_cap=np.linalg.inv(np.matmul(np.transpose(m),m))

In [138]:
b_cap

array([[ 0.33962098, -0.10902237],
       [-0.10902237,  0.03569822]])

In [139]:
b_cap1=np.matmul(np.matmul(b_cap,np.transpose(m)),y)

In [140]:
b_cap1

array([ 6.48122321, -0.20887029])

In [141]:
#calculating TSS

In [142]:
TSS=np.matmul(np.transpose(y),y)-150*(s.mean(y))**2

In [143]:
TSS

102.16833333333307

In [144]:
#calculating ESS

In [145]:
y_cap=np.matmul(m,b_cap1)

In [146]:
y_cap

array([5.75017718, 5.85461233, 5.81283827, 5.8337253 , 5.72929015,
       5.66662906, 5.77106421, 5.77106421, 5.87549936, 5.8337253 ,
       5.70840312, 5.77106421, 5.85461233, 5.85461233, 5.64574204,
       5.56219392, 5.66662906, 5.75017718, 5.68751609, 5.68751609,
       5.77106421, 5.70840312, 5.72929015, 5.79195124, 5.77106421,
       5.85461233, 5.77106421, 5.75017718, 5.77106421, 5.81283827,
       5.8337253 , 5.77106421, 5.62485501, 5.60396798, 5.8337253 ,
       5.81283827, 5.75017718, 5.8337253 , 5.85461233, 5.77106421,
       5.75017718, 6.00082154, 5.81283827, 5.75017718, 5.68751609,
       5.85461233, 5.68751609, 5.81283827, 5.70840312, 5.79195124,
       5.81283827, 5.81283827, 5.8337253 , 6.00082154, 5.89638639,
       5.89638639, 5.79195124, 5.97993451, 5.87549936, 5.91727342,
       6.06348262, 5.85461233, 6.02170856, 5.87549936, 5.87549936,
       5.8337253 , 5.85461233, 5.91727342, 6.02170856, 5.95904748,
       5.81283827, 5.89638639, 5.95904748, 5.89638639, 5.87549

In [147]:
ESS=np.matmul(np.transpose(y_cap),y_cap)-150*(s.mean(y_cap))**2

In [148]:
ESS

1.2221000906756672

In [149]:
#calculating R^2

In [150]:
RSS=TSS-ESS
RSS

100.9462332426574

In [157]:
r=np.divide(ESS,TSS)

In [158]:
r


0.011961632834789028

In [159]:
# ADUJSTED R-square 

In [164]:
df2=df[["SepalWidthCm","PetalLengthCm"]]
result=pd.concat([x,df2],axis=1)
m=pd.DataFrame.as_matrix(result,columns=None)
b_cap=np.linalg.inv(np.matmul(np.transpose(m),m))
b_cap1=np.matmul(np.matmul(b_cap,np.transpose(m)),y)
y_cap=np.matmul(m,b_cap1)
ESS=np.matmul(np.transpose(y_cap),y_cap)-150*(s.mean(y_cap))**2
RSS=TSS-ESS
RSS
r=np.divide(ESS,TSS)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [165]:
r

0.8403288642253651

In [166]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (8, 6)
plt.rcParams['font.size'] = 14

In [170]:
feature_cols=["SepalWidthCm","PetalLengthCm","PetalWidthCm"]
y=df.SepalLengthCm
X=df[feature_cols]

In [171]:
# import, instantiate, fit
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [175]:
 linreg.intercept_
 

1.845060803216616

In [176]:
linreg.coef_

array([ 0.65486424,  0.71106291, -0.56256786])

In [179]:
import statsmodels.formula.api as smf

lm=smf.ols('SepalLengthCm~SepalWidthCm+PetalLengthCm+PetalWidthCm', train).fit()

In [178]:
from sklearn.model_selection import train_test_split
train ,test = train_test_split(df,test_size=0.3,random_state = 123 ) 

In [180]:
lm

In [181]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:          SepalLengthCm   R-squared:                       0.858
Model:                            OLS   Adj. R-squared:                  0.854
Method:                 Least Squares   F-statistic:                     203.8
Date:                Mon, 10 Feb 2020   Prob (F-statistic):           1.08e-42
Time:                        20:51:58   Log-Likelihood:                -21.983
No. Observations:                 105   AIC:                             51.97
Df Residuals:                     101   BIC:                             62.58
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         1.8556      0.313      5.922      0.000       1.234       2.477
SepalWidthCm      0.6401      0.084      7.665      0.000       0.474       0.806
PetalLengthCm     0.7577      0.065     11.633      0.000       0.629       0.887
PetalWidthCm     -0.6871      0.145     -4.730      0.000      -0.975      -0.399
==============================================================================
Omnibus:                        2.141   Durbin-Watson:                   2.093
Prob(Omnibus):                  0.343   Jarque-Bera (JB):                2.173
Skew:                          -0.323   Prob(JB):                        0.337
Kurtosis:                       2.720   Cond. No.                         59.5
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [182]:
AIC=(np.divide(RSS,150))-2*2/150

In [183]:
AIC

0.0820888921568985